version: '3.8'

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    ports:
      - "80:80"
      - "443:443"
      - "9100:9100"
    environment:
      - LISTEN_ADDR=:443
      - METRICS_ADDR=:9100
      - ALLOWED_DOMAIN=${ALLOWED_DOMAIN}
      - SUPABASE_TARGET_DOMAIN=${SUPABASE_TARGET_DOMAIN}
      - ENFORCE_HTTPS=${ENFORCE_HTTPS:-true}
      - TLS_CERT_FILE=/tls/fullchain.pem
      - TLS_KEY_FILE=/tls/privkey.pem
    volumes:
      - /etc/letsencrypt/live/api.ariyanasoft.net:/tls:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9100/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 